apiVersion: v1
kind: Pod
metadata:
  name: redis-team-b
  namespace: team-b
spec:
  containers:
    - name: redis-team-b
      image: redis:latest
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "500m" 
          memory: "256Mi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000