apiVersion: v1
kind: Pod
metadata:
  name: alpine-test
  labels:
    app.kubernetes.io/name: alpine-test
spec:
  containers:
  - name: alpine-test
    image: alpine
    command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

