apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 5
  completions: 5 
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: parallel-job
        image: busybox
        command: ["echo",  "parallel", "job"]
      restartPolicy: Never
