apiVersion: batch/v1
kind: Job
metadata:
  name: date-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: date-bb
        image: busybox
        command: ["date"]
      restartPolicy: Never
