apiVersion: batch/v1
kind: CronJob
metadata:
  name: long-run-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - sleep 30
          restartPolicy: OnFailure
