apiVersion: batch/v1
kind: Job
metadata:
  name: retry-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: bb-3
        image: busybox
        command: ["sh","-c","exit 1"]
      restartPolicy: Never
